version: 0.2

phases:
  install:
    commands:
      - make dependencies-frontend

  pre_build:
    commands:
      - echo pre_build

  build:
    commands:
      - make build-frontend

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - cfn/*
    - config/*
    - frontend/build/**
